require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Include:
    - 'spec/**/*'
    - '**/Gemfile'
  Exclude:
    - 'lib/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'app/assets/builds/*'

Metrics/BlockLength:
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group
  Max: 40

# Layout / Style
Layout/LineLength:
  Exclude:
    - 'app/helpers/**/*'
    - 'config/routes.rb'
    - 'config/initializers/devise.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'app/admin/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'config/initializers/trestle.rb'

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/*'

Lint/RedundantDirGlobSort:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/helpers/**/*'
    - 'db/migrate/*'
  Max: 20

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/**/*'
    - 'db/migrate/*'
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/**/*'

Naming/FileName:
  Exclude:
    - 'Rakefile'

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

# Rails
Rails/FilePath:
  EnforcedStyle: arguments

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

# RSpec
RSpec/HookArgument:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/DescribedClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/requests/**/*.rb'

RSpec/InstanceVariable:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: module_function
